# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            YuiTycc的博客
tagline:          '倾听Ghost的低语'
description:      '请多多指教'
url:              https://yuitycc.me/
baseurl:          /
excerpt_separator: <!-- more -->


author:
  name:           'Junious'
  #url:            /
  #language: zh
  #timezone: Asia/Shanghai

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Gems
plugins: [jekyll-paginate, jekyll-gist]